on:
  push:
    branches:
      - master
      - 'releases/**'

name: "CI-Production"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3.0

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Configure composer for Laravel Nova
      run: |
        composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan migrate:fresh --seed --force
        php artisan passport:install --force

    - name: Run Testsuite
      run: vendor/bin/phpunit tests/

  dusk:
    runs-on: ubuntu-latest
    container: docker://zaherg/laravel-dusk:latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare the environment
        run: cp .env.example .env
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          php artisan key:generate
      - name: Run dusk tests
        run: |
          php artisan dusk:chrome-driver
          nohup bash -c './vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &'
          nohup bash -c 'php artisan serve > /dev/null 2>&1 &'
          php artisan dusk

  prepare_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install front-end dependencies
        run: |
          npm install
          npm run production

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Laravel Forge
        run: curl ${{ secrets.FORGE_DEPLOYMENT_WEBHOOK }}
